server:
  port: 0

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  cloud:
    openfeign:
      micrometer:
        enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: ecom
      username: esta
      password: '{cipher}AYCVoyHJ6INEzT4Hy+hVA09e00IqcZKJJXAfGqYmETrGh+aPn3kuQChhHfqUbYg2pzce3ASiYnCgfxqHOSU4Y2IqQIlDCAF2DCvE243aPPr+6rfITW5nAE9ETfqKCM/SSG1iWe4E6b+YfHfd8HSdGvsxPzPiPXid22fx8/t0yL5kXOepqstjxx4yf3Q3Mt2Ljxx0LYzNgV7O8Ioe6kKPkB0D26YZSV7Z1R5erbLF6G+JGVbxMgOayrQ9+GdxaFl2LvaYqzZmqur3p0mlXOP2/GKLXrrparceKHWgHT1AqBzZlemyRYHT18N8/CVYOhyD/ADbKwQek1UQs4e2VxKwPxrwbhV+YIsB5cx/XfBia6NJdzhu7cNoC/wgkYfP5uFPDOcalfCzJGe+1SvJGC4xcwwAaS1qBJFEXWER4VwSsY7ns9Hr5iFeb7JvmVJv89+SDwDpWwmk1XNCiVd+KxruBDySiDqgaF04PUurrKMpiPQlyPI8YMnj32ORIf4qOWwfNdmRd3A1dS4bNFHLwynGWyJMpIRA/nkL9srivtthy2mL5A=='

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh, prometheus, metrics
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

token:
  secret: '{cipher}AYBy1WybH76OlQNvu2n2dtpbPEjuH0LCdwLHeTodGb9f+i31GP+x37fNx0vXkgceVFA0abkCVq5oYa7TTrEcmykUSUihYlZWKVCD2EXBDRXApSKD0W4to84Jss42IaWtq5sd+uuESA2Tg32thr9eb1vfELekZ0RrkbDE6sTp8SrZN1h2NvpsqYUXOgO7WYgTsm49/BJ1aTCKSKRbwT1NpwGKo6s2q9XL9oaYghloBPTnS+TVDszVIPHLELypupcDFIxz3jmQQLN0rI0SCujw1G63ZPkubk8PTI1ZbB9j7n57U/MQ22w5P+bUbLWXznV/pmWXCCfrR3eV01Zyl5f2i0HukRhymSz8fcj6wBX7C1Cj+lrkjUP6BiGW7KLBG2npwRbuymMcUYmRJss9xjLbxk2I60Uyx05o751nJewtlPrFGIP2YjEhVwwLMSVovm6J/sTVtywQaKWopcnPjPOEoZiI2J9AhclE8+pGX9+nVWP4ENRgaYmwApFmsmGtePnE2SogAlTe8fHXoozPdztpcvVHywJMh9DmcY8klSI0m5hVKg2Fx2TAbx3p1dHCqL0XxuVc/twNHUvNAQ4MgnKQgQC/2IVE8na693+9IeHBYE6AVA=='
  expiration_time: 86500000

gateway:
  ip: localhost