spring:
  application:
    name: catalog-m-service
  datasource:
    url: jdbc:postgresql://psql:5432/ecommerce
    driver-class-name: org.postgresql.Driver
    username: '{cipher}AYB6G6j9rxZXvqBN5W31gOTt1E9QqMCVv3+O+z5rChkmGMxlTn+Ab5gbCIemxPvKBSS2am21xO7pYQVLRicYI+8LXa/eUj18EbueSFf6ls/0DCW807QW1IPkcAOKovTPgerGI0R5hveX3iUneco/wmBww23DxusAhW3ddpWnSFpJDfvRkmcBDDQ75zLWKXqmoV6e0SgeC+HP/Fhnj/gRc2XYM0pNx9TQTbxtk9o9PQY5S2haXRScSbcdJCS3ug6PC6K/jimoBT0W60F35P40QG0Urv1wQI+3nVkYJw64nV8svZt6xkJ4nC4LztKzOCVy43K9lo6epCr973E/j7k/eW+9NHu+BLzDPsyPyEVDygsLkS09m7vXPt3kQ1CSXnhxg43FSrR2B0Xo2aGT5fbf/SrzMd+K5w79SNFveUcEERzKO8JL9mgKFBHlzTotPYkHjNhB2oZXTMWiGeHhEsQGlUkJEeTHuASlDNVVnS2hmvkI7gNo+LsoRiJ+t/PycWvcRS5rhEIlHp+bL2PF2kHcpZ0A5qYYylmKz/Ov4WDAniMhug=='
    password: '{cipher}AYB6G6j9rxZXvqBN5W31gOTt1E9QqMCVv3+O+z5rChkmGMxlTn+Ab5gbCIemxPvKBSS2am21xO7pYQVLRicYI+8LXa/eUj18EbueSFf6ls/0DCW807QW1IPkcAOKovTPgerGI0R5hveX3iUneco/wmBww23DxusAhW3ddpWnSFpJDfvRkmcBDDQ75zLWKXqmoV6e0SgeC+HP/Fhnj/gRc2XYM0pNx9TQTbxtk9o9PQY5S2haXRScSbcdJCS3ug6PC6K/jimoBT0W60F35P40QG0Urv1wQI+3nVkYJw64nV8svZt6xkJ4nC4LztKzOCVy43K9lo6epCr973E/j7k/eW+9NHu+BLzDPsyPyEVDygsLkS09m7vXPt3kQ1CSXnhxg43FSrR2B0Xo2aGT5fbf/SrzMd+K5w79SNFveUcEERzKO8JL9mgKFBHlzTotPYkHjNhB2oZXTMWiGeHhEsQGlUkJEeTHuASlDNVVnS2hmvkI7gNo+LsoRiJ+t/PycWvcRS5rhEIlHp+bL2PF2kHcpZ0A5qYYylmKz/Ov4WDAniMhug=='

logging:
  level:
    service.catalogmservice: DEBUG
    