spring:
  application:
   name: order-m-service
  datasource:
    url: jdbc:postgresql://psql:5432/ecommerce
    driver-class-name: org.postgresql.Driver
    username: '{cipher}AYBK2lsrTvpglBy4xWJ9mMgnc/aa4/44k8LouzsaRuK6ppi5+8IMSizy/bz//wRTHolkJjBUjRQtX5hSiXXNSplso5/CZ0zeoRE9+88nCpsivYpngrgd6KBagW5vA0n+7SQkdfl64WLdmtcJnYjMdF1T7zWSmMHf5f9cMY+F2RZ0jrT8r9RwzMxpFA4r9+NgaMWVj58OGZebqNS4ZITDm2imtUq0HQdWG552sGJiYIY7hERUgWpORXa+h5lLy2iqROD9ECyA9DoEJv7yAHxLrHMXbpQRGQGP6lgDAembaXNj52Bt2YbzgUdeU6mbwEXekhjxa4PPf0AWxZ0rgRUIJaBwI/dzxA3aP19q+jGThP0saXETIo01xN8wm9+fzdrSo7SZcbBcLg23G+qoGaAJk9bmZ2DGK9+ChcDly+7XS8Uq0nn0Hu4wLRPd8cTekOM3Hy0Gl3VpIe3g6PRMDFNMp76A9EykoK5GInjcUj+nLmTu2g0cSCHbQ28ZZT5dwYlKL+T7LSpGSrQAhvw8D/AqoR3fsBbL2KGeLm1lhJf92g46XA=='
    password: '{cipher}AYBK2lsrTvpglBy4xWJ9mMgnc/aa4/44k8LouzsaRuK6ppi5+8IMSizy/bz//wRTHolkJjBUjRQtX5hSiXXNSplso5/CZ0zeoRE9+88nCpsivYpngrgd6KBagW5vA0n+7SQkdfl64WLdmtcJnYjMdF1T7zWSmMHf5f9cMY+F2RZ0jrT8r9RwzMxpFA4r9+NgaMWVj58OGZebqNS4ZITDm2imtUq0HQdWG552sGJiYIY7hERUgWpORXa+h5lLy2iqROD9ECyA9DoEJv7yAHxLrHMXbpQRGQGP6lgDAembaXNj52Bt2YbzgUdeU6mbwEXekhjxa4PPf0AWxZ0rgRUIJaBwI/dzxA3aP19q+jGThP0saXETIo01xN8wm9+fzdrSo7SZcbBcLg23G+qoGaAJk9bmZ2DGK9+ChcDly+7XS8Uq0nn0Hu4wLRPd8cTekOM3Hy0Gl3VpIe3g6PRMDFNMp76A9EykoK5GInjcUj+nLmTu2g0cSCHbQ28ZZT5dwYlKL+T7LSpGSrQAhvw8D/AqoR3fsBbL2KGeLm1lhJf92g46XA=='

logging:
  level:
    service.ordermservice.client: DEBUG
    