spring:
  application:
    name: user-m-service
  datasource:
    url: jdbc:postgresql://psql:5432/users
    driver-class-name: org.postgresql.Driver
    username: '{cipher}AYB+TphtPv1h3tftXw8kF9XI+7HtAcp3bq2ScB4QLquc6CWKblt4Hh6hA36Prupn06m7D3lsklVMopqrEnJHc5XTi7tvQQpjPTbCjPqRa7veo++TvkpYPvfNd2GLtNB3lcTw3Truk6zPE+bpcFtQrW/2v0UnOiwQBotUDIyFBB9rgA8mEOcYI+bhfegaW0TFPcMIytu4qOB89SWj9J6weiLhoslDjp51ntTO1iZ6biQI5ri/C8jYiCpPz19ufDzBnFU7knl5qADgkWyCS94VkiXNxLHIII79nJgj3i4idN7R6wKD9iWNR0JgJNkM2vfGR8M8m0wGroSRgx0TPht5YTapjOjO4kIeUQuPD1WH2uP7YkuQdyGzxK2H1qqYuiMAejPROgnTbcjD+MCkH4YCgo5/dj1kis426Zk5X4GZ//ubzcki1l+jzPQ6b+dkwBRJPqbRDDuBQ138U2yiYVV9+n86R0oBDLd3CGt0JDWa6AN3htBIB04kdHF0V15I4cpH2AKiyi2jhUGoST+0oV1pSygdSht8tIK7Ycmr4vO4dlNKfQ=='
    password: '{cipher}AYB+TphtPv1h3tftXw8kF9XI+7HtAcp3bq2ScB4QLquc6CWKblt4Hh6hA36Prupn06m7D3lsklVMopqrEnJHc5XTi7tvQQpjPTbCjPqRa7veo++TvkpYPvfNd2GLtNB3lcTw3Truk6zPE+bpcFtQrW/2v0UnOiwQBotUDIyFBB9rgA8mEOcYI+bhfegaW0TFPcMIytu4qOB89SWj9J6weiLhoslDjp51ntTO1iZ6biQI5ri/C8jYiCpPz19ufDzBnFU7knl5qADgkWyCS94VkiXNxLHIII79nJgj3i4idN7R6wKD9iWNR0JgJNkM2vfGR8M8m0wGroSRgx0TPht5YTapjOjO4kIeUQuPD1WH2uP7YkuQdyGzxK2H1qqYuiMAejPROgnTbcjD+MCkH4YCgo5/dj1kis426Zk5X4GZ//ubzcki1l+jzPQ6b+dkwBRJPqbRDDuBQ138U2yiYVV9+n86R0oBDLd3CGt0JDWa6AN3htBIB04kdHF0V15I4cpH2AKiyi2jhUGoST+0oV1pSygdSht8tIK7Ycmr4vO4dlNKfQ=='

logging:
  level:
    service.usermservice.client: DEBUG

order_service:
  url: http://ORDER-M-SERVICE/order-m-service/%s/orders
  exception:
    order_empty: There is no item.